//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class marketEntities : DbContext
    {
        public marketEntities()
            : base("name=marketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Basket> Basket { get; set; }
        public DbSet<History> History { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<ViewBasket> ViewBasket { get; set; }
    
        public virtual ObjectResult<GiveMeBasket_Result> GiveMeBasket(Nullable<int> numb)
        {
            var numbParameter = numb.HasValue ?
                new ObjectParameter("numb", numb) :
                new ObjectParameter("numb", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiveMeBasket_Result>("GiveMeBasket", numbParameter);
        }
    }
}
